from __future__ import annotations

ALLOWED_PREFIXES = ("light-", "fridge-", "temp-", "setpoint-")

_HEADER = '''"""AUTO-GENERATED by open-california. Own-vehicle interoperability use.
Safety functions (heater, roof) are intentionally excluded.
Run on a Raspberry Pi with BlueZ: `python replay.py light-on`."""
import asyncio, sys
from bleak import BleakClient

ADDRESS = "{address}"
COMMANDS = {{
{commands}
}}

async def main(action: str) -> None:
    char, payload = COMMANDS[action]
    async with BleakClient(ADDRESS) as client:
        await client.write_gatt_char(char, payload, response=False)
        print(f"sent {{action}} -> {{payload.hex()}}")

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in COMMANDS:
        raise SystemExit(f"usage: python replay.py <{{'|'.join(COMMANDS)}}>")
    asyncio.run(main(sys.argv[1]))
'''

def generate(mapping: dict, address: str) -> str:
    lines = []
    for action, spec in sorted(mapping.get("actions", {}).items()):
        if not action.startswith(ALLOWED_PREFIXES):
            continue
        if not spec.get("confirmed"):
            continue
        uuid = spec.get("uuid")
        char = f'"{uuid}"' if uuid else spec["handle"]
        lines.append(f'    "{action}": ({char}, bytes.fromhex("{spec["value"]}")),')
    if not lines:
        raise ValueError("no confirmed, allowed actions to generate")
    return _HEADER.format(address=address, commands="\n".join(lines))
