from __future__ import annotations
import re

ALLOWED_PREFIXES = ("light-", "fridge-", "temp-", "setpoint-")

_ACTION_RE = re.compile(r"^[a-z0-9-]+$")
_UUID_RE = re.compile(r"^[0-9a-fA-F-]+$")
_HEX_RE = re.compile(r"^[0-9a-fA-F]*$")

_HEADER = '''"""AUTO-GENERATED by open-california. Own-vehicle interoperability use.
Safety functions (heater, roof) are intentionally excluded.
Run on a Raspberry Pi with BlueZ: `python replay.py light-on`."""
import asyncio, sys
from bleak import BleakClient

ADDRESS = "{address}"
COMMANDS = {{
{commands}
}}

async def main(action: str) -> None:
    char, payload = COMMANDS[action]
    async with BleakClient(ADDRESS) as client:
        await client.write_gatt_char(char, payload, response=False)
        print(f"sent {{action}} -> {{payload.hex()}}")

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in COMMANDS:
        raise SystemExit(f"usage: python replay.py <{{'|'.join(COMMANDS)}}>")
    asyncio.run(main(sys.argv[1]))
'''

def generate(mapping: dict, address: str) -> str:
    lines = []
    for action, spec in sorted(mapping.get("actions", {}).items()):
        if not action.startswith(ALLOWED_PREFIXES):
            continue
        if not spec.get("confirmed"):
            continue

        # Validate action slug
        if not _ACTION_RE.match(action):
            raise ValueError(f"unsafe action slug: {action!r}")

        # Validate uuid and handle
        uuid = spec.get("uuid")
        if uuid is None and "handle" not in spec:
            raise ValueError(f"action {action} has neither uuid nor handle")
        if uuid is not None and not _UUID_RE.match(uuid):
            raise ValueError(f"unsafe uuid for {action}: {uuid!r}")

        # Validate hex value
        hexval = spec["value"]
        if not _HEX_RE.match(hexval):
            raise ValueError(f"unsafe hex value for {action}: {hexval!r}")

        char = f'"{uuid}"' if uuid else spec["handle"]
        lines.append(f'    "{action}": ({char}, bytes.fromhex("{hexval}")),')
    if not lines:
        raise ValueError("no confirmed, allowed actions to generate")
    return _HEADER.format(address=address, commands="\n".join(lines))
