"""The generated C dictionary header stays in lockstep with dictionary.yaml.

``csrc/codec_dict.h`` is generated by ``tools/gen_c_dict.py`` and checked in; this
test regenerates it in memory and asserts byte-equality, so a dictionary/overrides
edit without a header regen fails CI (same guard the ``--check`` CLI flag gives CI
directly).

.. test:: Checked-in C dictionary header matches a fresh regeneration
   :id: T_CDICT_REGEN_FRESH
   :links: R_DICT_SINGLE_SOURCE
"""
from pathlib import Path

from calictl import overrides
from tools import gen_c_dict

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "csrc" / "codec_dict.h"


def test_checked_in_header_is_fresh():
    assert gen_c_dict.generate() == HEADER.read_text()


def test_every_pinned_control_function_has_a_table():
    text = HEADER.read_text()
    for fn in overrides.CONTROL_FRAME_BYTES:
        assert ("%s_CTRL" % fn.upper()) in text, fn


def test_header_is_protocol_facts_only():
    # no decompiled-source identifiers leak into the generated artifact
    text = HEADER.read_text()
    assert ".java" not in text and "decompile" not in text.lower()


def test_chars_header_is_fresh_and_covers_every_state_function():
    """The checked-in ``codec_chars.h`` matches a fresh ``generate_chars()`` regeneration
    and carries a row for every function with a state char.

    .. test:: Generated char-map header is fresh and covers every state function
       :id: T_CDICT_CHARS_FRESH
       :links: R_CHARS_PAIRING_SINGLE_SOURCE
    """
    from calictl import overrides, protocol
    from tools import gen_c_dict

    text = gen_c_dict.generate_chars()
    assert text == (ROOT / "csrc" / "codec_chars.h").read_text()
    funcs = protocol.load()
    overrides.apply(funcs)
    for name, f in funcs.items():
        if f.state_char:
            short = str(f.state_char)[4:8].lower()
            assert '{"%s", 0x%s}' % (name, short) in text


def test_pairing_header_mirrors_calictl_pairing():
    """The checked-in ``pairing_consts.h`` matches a fresh ``generate_pairing()``
    regeneration and mirrors ``calictl.pairing``'s pinned enums/timeouts.

    .. test:: Generated pairing header mirrors calictl.pairing
       :id: T_CDICT_PAIRING_FRESH
       :links: R_CHARS_PAIRING_SINGLE_SOURCE
    """
    from calictl import pairing as P
    from tools import gen_c_dict

    text = gen_c_dict.generate_pairing()
    assert text == (ROOT / "csrc" / "pairing_consts.h").read_text()
    assert "PAIR_MAX_ATTEMPTS %d" % P.MAX_ATTEMPTS in text
    assert "PAIR_EV_CONNECT_FAIL = %d" % P.EV_CONNECT_FAIL in text
    for st, secs in P.TIMEOUT_S.items():
        assert "[PAIR_%s] = %d" % (P.STATE_NAMES[st].upper(), secs) in text


def test_chars_header_device_name_matches_the_single_source_of_truth():
    """``CODEC_DEVICE_NAME`` is never hand-typed in the generator — it must equal
    ``calictl.device.DEVICE_NAME``, the same constant ``calictl.pairing_bluez``'s
    ``BluezTransport`` uses as its default scan-name filter.
    """
    import inspect

    from calictl import device, pairing_bluez
    from tools import gen_c_dict

    text = gen_c_dict.generate_chars()
    assert 'CODEC_DEVICE_NAME "%s"' % device.DEVICE_NAME in text
    default = inspect.signature(pairing_bluez.BluezTransport.__init__).parameters["device_name"].default
    assert default == device.DEVICE_NAME
