"""The generated C dictionary header stays in lockstep with dictionary.yaml.

``csrc/codec_dict.h`` is generated by ``tools/gen_c_dict.py`` and checked in; this
test regenerates it in memory and asserts byte-equality, so a dictionary/overrides
edit without a header regen fails CI (same guard the ``--check`` CLI flag gives CI
directly).

.. test:: Checked-in C dictionary header matches a fresh regeneration
   :id: T_CDICT_REGEN_FRESH
   :links: R_DICT_SINGLE_SOURCE
"""

from pathlib import Path

from calictl import overrides
from tools import gen_c_dict

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "csrc" / "codec_dict.h"


def test_checked_in_header_is_fresh():
    assert gen_c_dict.generate() == HEADER.read_text()


def test_every_pinned_control_function_has_a_table():
    text = HEADER.read_text()
    for fn in overrides.CONTROL_FRAME_BYTES:
        assert ("%s_CTRL" % fn.upper()) in text, fn


def test_header_is_protocol_facts_only():
    # no decompiled-source identifiers leak into the generated artifact
    text = HEADER.read_text()
    assert ".java" not in text and "decompile" not in text.lower()


def test_chars_header_is_fresh_and_covers_every_state_function():
    """The checked-in ``codec_chars.h`` matches a fresh ``generate_chars()`` regeneration
    and carries a row for every function with a state char.

    .. test:: Generated char-map header is fresh and covers every state function
       :id: T_CDICT_CHARS_FRESH
       :links: R_CHARS_PAIRING_SINGLE_SOURCE
    """
    from calictl import overrides, protocol
    from tools import gen_c_dict

    text = gen_c_dict.generate_chars()
    assert text == (ROOT / "csrc" / "codec_chars.h").read_text()
    funcs = protocol.load()
    overrides.apply(funcs)
    for name, f in funcs.items():
        if f.state_char:
            short = str(f.state_char)[4:8].lower()
            assert '{"%s", 0x%s}' % (name, short) in text


def test_pairing_header_mirrors_calictl_pairing():
    """The checked-in ``pairing_consts.h`` matches a fresh ``generate_pairing()``
    regeneration and mirrors ``calictl.pairing``'s pinned enums/timeouts.

    .. test:: Generated pairing header mirrors calictl.pairing
       :id: T_CDICT_PAIRING_FRESH
       :links: R_CHARS_PAIRING_SINGLE_SOURCE
    """
    from calictl import pairing as P
    from tools import gen_c_dict

    text = gen_c_dict.generate_pairing()
    assert text == (ROOT / "csrc" / "pairing_consts.h").read_text()
    assert "PAIR_MAX_ATTEMPTS %d" % P.MAX_ATTEMPTS in text
    assert "PAIR_EV_CONNECT_FAIL = %d" % P.EV_CONNECT_FAIL in text
    for st, secs in P.TIMEOUT_S.items():
        assert "[PAIR_%s] = %d" % (P.STATE_NAMES[st].upper(), secs) in text


def test_chars_header_device_name_matches_the_single_source_of_truth():
    """``CODEC_DEVICE_NAME`` is never hand-typed in the generator — it must equal
    ``calictl.device.DEVICE_NAME``, the same constant ``calictl.pairing_bluez``'s
    ``BluezTransport`` uses as its default scan-name filter.
    """
    import inspect

    from calictl import device, pairing_bluez
    from tools import gen_c_dict

    text = gen_c_dict.generate_chars()
    assert 'CODEC_DEVICE_NAME "%s"' % device.DEVICE_NAME in text
    default = inspect.signature(pairing_bluez.BluezTransport.__init__).parameters["device_name"].default
    assert default == device.DEVICE_NAME


def test_chars_header_heartbeat_timing_is_calictl_defaults_not_env(monkeypatch):
    """``CODEC_HEARTBEAT_PERIOD_MS`` / ``CODEC_HEARTBEAT_WARMUP_MS`` are the documented defaults
    of ``calictl.device.HEARTBEAT_PERIOD_S`` / ``HEARTBEAT_WARMUP_S`` (read from the source), so a
    developer's ``CALICTL_HEARTBEAT_*_S`` override never leaks into the committed header.

    .. test:: Generated heartbeat timing follows calictl's defaults, not the environment
       :id: T_CDICT_HEARTBEAT_TIMING
       :links: R_CHARS_PAIRING_SINGLE_SOURCE
    """
    import os
    import subprocess
    import sys

    from tools import gen_c_dict

    env = {k: v for k, v in os.environ.items() if not k.startswith("CALICTL_HEARTBEAT_")}
    probe = subprocess.run(  # the defaults as calictl itself resolves them with no override
        [
            sys.executable,
            "-c",
            "from calictl import device as d; "
            "print(round(d.HEARTBEAT_PERIOD_S * 1000), round(d.HEARTBEAT_WARMUP_S * 1000))",
        ],
        cwd=ROOT,
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )
    want_period, want_warmup = map(int, probe.stdout.split())
    monkeypatch.setenv("CALICTL_HEARTBEAT_PERIOD_S", "0.05")
    monkeypatch.setenv("CALICTL_HEARTBEAT_WARMUP_S", "0.1")
    text = gen_c_dict.generate_chars()
    assert "#define CODEC_HEARTBEAT_PERIOD_MS %d\n" % want_period in text
    assert "#define CODEC_HEARTBEAT_WARMUP_MS %d\n" % want_warmup in text
    assert want_warmup == 2000  # value-freshness.md: the proven on-device warm-up


def test_net_consts_header_is_fresh():
    """The checked-in ``net_consts.h`` matches a fresh ``generate_net()`` regeneration of
    ``tools.wifi_consts.CONSTS`` (#154 Task 1).

    .. test:: Generated network-constants header is fresh
       :id: T_CDICT_NET_FRESH
       :links: R_NET_CONSTS_SINGLE_SOURCE
    """
    from tools import gen_c_dict

    text = gen_c_dict.generate_net()
    assert text == (ROOT / "csrc" / "net_consts.h").read_text()
    assert '#define NET_AP_SSID "calictl-esp-setup"' in text
    assert "#define NET_SETUP_AFTER_MS 300000" in text


def test_net_consts_header_pins_the_wifi_sm_enums():
    """``net_consts.h`` carries the WiFi SM's pinned enums, read off ``tools.wifi_sm_ref`` (#154
    Task 3) — every ``WIFI_*``/``WEV_*``/``WACT_*`` member with its Python value, nothing else.

    .. test:: Generated network header pins the WiFi SM enums from the Python twin
       :id: T_CDICT_NET_WIFI_SM_ENUMS
       :links: R_NET_CONSTS_SINGLE_SOURCE
    """
    from tools import gen_c_dict
    from tools import wifi_sm_ref as W

    text = gen_c_dict.generate_net()
    for prefix, n in (("WIFI_", 6), ("WEV_", 9), ("WACT_", 7)):
        members = gen_c_dict._int_members(W, prefix)
        assert [v for _, v in members] == list(range(n)), prefix
        for name, val in members:
            assert "    %s = %d" % (name, val) in text
    assert "    WIFI_SETUP_AP_RETRYING = 5" in text
    assert "    WEV_TICK = 8" in text
    assert "    WACT_LOG_REASON = 6" in text
    assert "#define WIFI_MAX_ACTIONS %d" % W.MAX_ACTIONS in text
