"""The generated C dictionary header stays in lockstep with dictionary.yaml.

``csrc/codec_dict.h`` is generated by ``tools/gen_c_dict.py`` and checked in; this
test regenerates it in memory and asserts byte-equality, so a dictionary/overrides
edit without a header regen fails CI (same guard the ``--check`` CLI flag gives CI
directly).

.. test:: Checked-in C dictionary header matches a fresh regeneration
   :id: T_CDICT_REGEN_FRESH
   :links: R_DICT_SINGLE_SOURCE
"""
from pathlib import Path

from calictl import overrides
from tools import gen_c_dict

HEADER = Path(__file__).parent.parent / "csrc" / "codec_dict.h"


def test_checked_in_header_is_fresh():
    assert gen_c_dict.generate() == HEADER.read_text()


def test_every_pinned_control_function_has_a_table():
    text = HEADER.read_text()
    for fn in overrides.CONTROL_FRAME_BYTES:
        assert ("%s_CTRL" % fn.upper()) in text, fn


def test_header_is_protocol_facts_only():
    # no decompiled-source identifiers leak into the generated artifact
    text = HEADER.read_text()
    assert ".java" not in text and "decompile" not in text.lower()
