/* cali_wifi_sm.h — C twin of tools/wifi_sm_ref.py's WiFi provisioning/connectivity state machine
 * (#154 Task 3).
 *
 * (sphinx-needs cannot parse this C comment; the test object lives in the Python shim docstring of
 * tests/firmware/test_wifi_sm_parity.py — T_FW_WIFI_SM_PARITY -> R_FW_WIFI_PROVISION. See
 * firmware/README.md's traceability section.)
 *
 * Same contract as the Python twin: no strings, no radio, no clock in the SM. Time enters only as
 * WEV_TICK's arg (now_ms, monotonic ms since boot); WEV_FAILED's arg is the reason code; every other
 * event carries no arg. A transition that starts a clock leaves since_ms = 0 ("unstamped") and the
 * next TICK stamps it. Enum values (WIFI_*, WEV_*, WACT_*) and timings (NET_*_MS) are pinned in
 * csrc/net_consts.h (GENERATED by tools/gen_c_dict.py) — never renumber by hand.
 *
 * C99, no malloc, no platform deps: compiles on a host for the parity test
 * (tests/firmware/test_wifi_sm_parity.py, replaying tests/vectors/wifi_sm.json) and under ESP-IDF.
 */
#ifndef CALI_WIFI_SM_H
#define CALI_WIFI_SM_H
#include <stdint.h>

#include "net_consts.h"

typedef struct {
    uint8_t act;   /* WACT_* */
    uint32_t arg;  /* the reason for WACT_LOG_REASON; 0 otherwise */
} cali_wifi_action_t;

typedef struct {
    uint8_t st;           /* WIFI_* */
    uint8_t ap_up;        /* 1 once the SM emitted WACT_AP_START, 0 after WACT_AP_STOP */
    uint8_t joined_once;  /* 1 = creds joined or were loaded from flash (a FAILED retries); 0 = typed
                           * in this setup flow via WEV_CREDS_SET (a FAILED clears them) — ruling R6 */
    uint32_t retry_ms;    /* current backoff interval while (SETUP_AP_)RETRYING */
    uint64_t since_ms;    /* when ONLINE/RETRYING began; 0 = not stamped by a TICK yet */
    uint64_t next_try_ms; /* next STA_START while retrying */
} cali_wifi_state_t;

/* Advance the SM by one event.
 *
 * :param s: current state, updated in place.
 * :param ev: one of the ``WEV_*`` constants; unknown events are no-ops.
 * :param arg: ``now_ms`` for ``WEV_TICK``, the reason for ``WEV_FAILED``; unused otherwise.
 * :param out: receives up to ``WIFI_MAX_ACTIONS`` actions to run, in order.
 * :returns: the number of actions written to ``out``.
 */
int cali_wifi_step(cali_wifi_state_t *s, uint8_t ev, uint64_t arg,
                   cali_wifi_action_t out[WIFI_MAX_ACTIONS]);

#endif /* CALI_WIFI_SM_H */
