#!/usr/bin/env python3
"""Generate ``csrc/codec_dict.h`` — const C field tables from the protocol dictionary.

One source of truth, two consumers: :mod:`calictl.protocol` loads
``protocol/dictionary.yaml`` (+ :mod:`calictl.overrides`) at runtime; the C codec
(``csrc/codec.c``, consumed by the ESP32 port #154) gets the same facts as generated
static tables. The header is checked in; regenerate after ANY dictionary/overrides
change and never hand-edit it:

    python3 -m tools.gen_c_dict            # rewrite csrc/codec_dict.h
    python3 -m tools.gen_c_dict --check    # exit 1 if the checked-in header is stale

Generation rules (mirroring the Python codec's behaviour exactly):

- state tables carry **placed fields only** (``MERGED_AMBIGUOUS``/``UNKNOWN`` are
  omitted — decode parity with :func:`calictl.protocol.decode`);
- control tables are emitted only for functions with a pinned frame length
  (``overrides.CONTROL_FRAME_BYTES``), and generation **asserts every control field
  of those functions is placed** — a future unplaced field fails loudly here rather
  than emitting a half-frame table;
- ``valid`` sets become a 32-bit membership mask (asserted: every allowed value
  < 32; holds today — max is lighting Mode 28);
- output is deterministic (sorted function order), protocol facts only.

.. req:: The protocol dictionary is the single source for Python and C
   :id: R_DICT_SINGLE_SOURCE
   :status: implemented
   :tags: protocol, codec, esp32

   ``calictl`` shall derive the C codec's field tables from
   ``protocol/dictionary.yaml`` (+ overrides) via a maintained generator whose
   checked-in output is verified fresh in CI, so protocol edits reach both
   languages in lockstep and the generated header is never hand-edited.
"""
from __future__ import annotations

import sys
from pathlib import Path

from calictl import overrides, protocol

OUT = Path(__file__).resolve().parent.parent / "csrc" / "codec_dict.h"

_HEADER = """\
/* codec_dict.h — GENERATED by tools/gen_c_dict.py from protocol/dictionary.yaml
 * (+ calictl/overrides.py). Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef CODEC_DICT_H
#define CODEC_DICT_H
#include <stdint.h>

#define CODEC_F_HAS_DEFAULT 0x01
#define CODEC_F_HAS_VALID   0x02  /* valid_mask bit v set => raw value v allowed */

typedef struct {
    const char *name;
    uint16_t offset;      /* bit offset, MSB-first */
    uint8_t  width;       /* 1..32 bits */
    uint8_t  flags;
    uint32_t def;         /* raw default when CODEC_F_HAS_DEFAULT */
    uint32_t valid_mask;  /* when CODEC_F_HAS_VALID */
} codec_field_t;

typedef struct {
    const char *name;
    uint8_t frame_bytes;  /* pinned control frame length; 0 = no control frame */
    const codec_field_t *state_fields;
    uint8_t n_state;
    const codec_field_t *ctrl_fields;
    uint8_t n_ctrl;
} codec_func_t;
"""


def _field_row(f) -> str:
    flags, dflt, mask = [], 0, 0
    if isinstance(f.default, int):
        flags.append("CODEC_F_HAS_DEFAULT")
        dflt = f.default
    if f.valid is not None:
        allowed = (f.valid if isinstance(f.valid, (set, frozenset))
                   else range(f.valid[0], f.valid[1] + 1))
        assert max(allowed) < 32, \
            "%s valid value %d >= 32: widen valid_mask" % (f.name, max(allowed))
        for v in allowed:
            mask |= 1 << v
        flags.append("CODEC_F_HAS_VALID")
    return '    {"%s", %d, %d, %s, %du, 0x%08xu},' % (
        f.name, f.offset, f.width, "|".join(flags) or "0", dflt, mask)


def generate() -> str:
    funcs = protocol.load()
    overrides.apply(funcs)
    out = [_HEADER]
    max_fields = 0
    for name in sorted(funcs):
        fn = funcs[name]
        state = [f for f in fn.state_fields if f.placed]
        if state:
            out.append("static const codec_field_t %s_STATE[] = {" % name.upper())
            out.extend(_field_row(f) for f in state)
            out.append("};")
        if name in overrides.CONTROL_FRAME_BYTES:
            unplaced = [f.name for f in fn.control_fields if not f.placed]
            assert not unplaced, \
                "%s: unplaced control fields %s — a pinned-length function must be " \
                "fully placed (fix overrides), refusing a half-frame table" % (name, unplaced)
            out.append("static const codec_field_t %s_CTRL[] = {" % name.upper())
            out.extend(_field_row(f) for f in fn.control_fields)
            out.append("};")
            max_fields = max(max_fields, len(fn.control_fields))
        max_fields = max(max_fields, len(state))
    out.append("\nstatic const codec_func_t CODEC_FUNCS[] = {")
    for name in sorted(funcs):
        fn = funcs[name]
        state = [f for f in fn.state_fields if f.placed]
        fb = overrides.CONTROL_FRAME_BYTES.get(name, 0)
        s_tbl = "%s_STATE" % name.upper() if state else "0"
        c_tbl = "%s_CTRL" % name.upper() if fb else "0"
        n_ctrl = len(fn.control_fields) if fb else 0
        out.append('    {"%s", %d, %s, %d, %s, %d},'
                   % (name, fb, s_tbl, len(state), c_tbl, n_ctrl))
    out.append("};")
    out.append("#define CODEC_NFUNCS %d" % len(funcs))
    out.append("#define CODEC_MAX_FIELDS %d" % max_fields)
    out.append("#define CODEC_MAX_FRAME 32  /* bytes; largest real frame is lighting (16) */")
    out.append("#endif /* CODEC_DICT_H */")
    return "\n".join(out) + "\n"


def main() -> int:
    text = generate()
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != text:
            print("STALE: %s does not match a fresh regeneration — run "
                  "python3 -m tools.gen_c_dict" % OUT, file=sys.stderr)
            return 1
        print("fresh: %s" % OUT)
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
