#!/usr/bin/env python3
"""Generate the GENERATED C headers — const C field/char/pairing-SM tables from the
protocol dictionary and the pairing state machine.

One source of truth, two consumers: :mod:`calictl.protocol` loads
``protocol/dictionary.yaml`` (+ :mod:`calictl.overrides`) at runtime; the C codec
(``csrc/codec.c``, consumed by the ESP32 port #154) gets the same facts as generated
static tables. The headers are checked in; regenerate after ANY dictionary/overrides/
pairing/heartbeat change and never hand-edit them:

    python3 -m tools.gen_c_dict            # rewrite every generated file
    python3 -m tools.gen_c_dict --check    # exit 1 if any checked-in generated file is stale

Generation rules (mirroring the Python codec's behaviour exactly):

- state tables carry **placed fields only** (``MERGED_AMBIGUOUS``/``UNKNOWN`` are
  omitted — decode parity with :func:`calictl.protocol.decode`);
- control tables are emitted only for functions with a pinned frame length
  (``overrides.CONTROL_FRAME_BYTES``), and generation **asserts every control field
  of those functions is placed** — a future unplaced field fails loudly here rather
  than emitting a half-frame table;
- ``valid`` sets become a 32-bit membership mask (asserted: every allowed value
  < 32; holds today — max is lighting Mode 28);
- output is deterministic (sorted function order), protocol facts only.

``codec_chars.h`` and ``pairing_consts.h`` extend this to the ESP32 firmware's other
two needs: the GATT characteristic map (``calictl.protocol`` state chars + the aux
chars/heartbeat constants from :mod:`calictl.device`) and the pinned pairing
state-machine enums/timeouts/names from :mod:`calictl.pairing`. ``net_consts.h`` carries the WiFi
setup constants (:mod:`tools.wifi_consts`), and ``firmware/web/strings_gen.h`` +
``firmware/web/index_gen.html`` the firmware status/setup page rendered from
``firmware/web/index.html`` + ``strings.json``.

.. req:: The protocol dictionary is the single source for Python and C
   :id: R_DICT_SINGLE_SOURCE
   :status: implemented
   :tags: protocol, codec, esp32

   ``calictl`` shall derive the C codec's field tables from
   ``protocol/dictionary.yaml`` (+ overrides) via a maintained generator whose
   checked-in output is verified fresh in CI, so protocol edits reach both
   languages in lockstep and the generated header is never hand-edited.

.. req:: The GATT char map and pairing-SM constants are generated for C too
   :id: R_CHARS_PAIRING_SINGLE_SOURCE
   :status: implemented
   :tags: protocol, codec, esp32, pairing

   ``calictl`` shall derive the ESP32 firmware's GATT characteristic map
   (``codec_chars.h``) and pairing state-machine constants (``pairing_consts.h``)
   from :mod:`calictl.protocol`/:mod:`calictl.device` and :mod:`calictl.pairing`
   respectively, via the same generator and freshness gate as ``codec_dict.h``, so
   a pairing-SM or heartbeat-constant edit can never silently drift from the C port.
"""

from __future__ import annotations

import sys
from pathlib import Path

from calictl import overrides, protocol

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "csrc" / "codec_dict.h"
CHARS_OUT = ROOT / "csrc" / "codec_chars.h"
PAIRING_OUT = ROOT / "csrc" / "pairing_consts.h"
NET_OUT = ROOT / "csrc" / "net_consts.h"
WEB_DIR = ROOT / "firmware" / "web"
WEB_STRINGS_OUT = WEB_DIR / "strings_gen.h"
WEB_PAGE_OUT = WEB_DIR / "index_gen.html"

_HEADER = """\
/* codec_dict.h — GENERATED by tools/gen_c_dict.py from protocol/dictionary.yaml
 * (+ calictl/overrides.py). Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef CODEC_DICT_H
#define CODEC_DICT_H
#include <stdint.h>

#define CODEC_F_HAS_DEFAULT 0x01
#define CODEC_F_HAS_VALID   0x02  /* valid_mask bit v set => raw value v allowed */

/* Plain struct tags (no typedefs — codec.h owns the codec_func_t typedef and
 * forward-declares the tag, C99-clean): these static tables stay private to
 * codec.c, the only includer of this header. */
struct codec_field {
    const char *name;
    uint16_t offset;      /* bit offset, MSB-first */
    uint8_t  width;       /* 1..32 bits */
    uint8_t  flags;
    uint32_t def;         /* raw default when CODEC_F_HAS_DEFAULT */
    uint32_t valid_mask;  /* when CODEC_F_HAS_VALID */
};

struct codec_func {
    const char *name;
    uint8_t frame_bytes;  /* pinned control frame length; 0 = no control frame */
    const struct codec_field *state_fields;
    uint8_t n_state;
    const struct codec_field *ctrl_fields;
    uint8_t n_ctrl;
};
"""


def _field_row(f) -> str:
    assert 1 <= f.width <= 32, "%s: width %d exceeds the uint32 field model" % (f.name, f.width)
    flags, dflt, mask = [], 0, 0
    if isinstance(f.default, int):
        flags.append("CODEC_F_HAS_DEFAULT")
        dflt = f.default
    if f.valid is not None:
        allowed = f.valid if isinstance(f.valid, (set, frozenset)) else range(f.valid[0], f.valid[1] + 1)
        assert max(allowed) < 32, "%s valid value %d >= 32: widen valid_mask" % (f.name, max(allowed))
        for v in allowed:
            mask |= 1 << v
        flags.append("CODEC_F_HAS_VALID")
    return '    {"%s", %d, %d, %s, %du, 0x%08xu},' % (
        f.name,
        f.offset,
        f.width,
        "|".join(flags) or "0",
        dflt,
        mask,
    )


def generate() -> str:
    funcs = protocol.load()
    overrides.apply(funcs)
    out = [_HEADER]
    max_fields = 0
    for name in sorted(funcs):
        fn = funcs[name]
        state = [f for f in fn.state_fields if f.placed]
        if state:
            out.append("static const struct codec_field %s_STATE[] = {" % name.upper())
            out.extend(_field_row(f) for f in state)
            out.append("};")
        if name in overrides.CONTROL_FRAME_BYTES:
            unplaced = [f.name for f in fn.control_fields if not f.placed]
            assert not unplaced, (
                "%s: unplaced control fields %s — a pinned-length function must be "
                "fully placed (fix overrides), refusing a half-frame table" % (name, unplaced)
            )
            out.append("static const struct codec_field %s_CTRL[] = {" % name.upper())
            out.extend(_field_row(f) for f in fn.control_fields)
            out.append("};")
            max_fields = max(max_fields, len(fn.control_fields))
        max_fields = max(max_fields, len(state))
    out.append("\nstatic const struct codec_func CODEC_FUNCS[] = {")
    for name in sorted(funcs):
        fn = funcs[name]
        state = [f for f in fn.state_fields if f.placed]
        fb = overrides.CONTROL_FRAME_BYTES.get(name, 0)
        s_tbl = "%s_STATE" % name.upper() if state else "0"
        c_tbl = "%s_CTRL" % name.upper() if fb else "0"
        n_ctrl = len(fn.control_fields) if fb else 0
        out.append('    {"%s", %d, %s, %d, %s, %d},' % (name, fb, s_tbl, len(state), c_tbl, n_ctrl))
    out.append("};")
    out.append("#define CODEC_NFUNCS %d" % len(funcs))
    out.append("#define CODEC_MAX_FIELDS %d" % max_fields)
    out.append("#define CODEC_MAX_FRAME 32  /* bytes; largest real frame is lighting (16) */")
    out.append("#endif /* CODEC_DICT_H */")
    return "\n".join(out) + "\n"


_CHARS_HEADER = """\
/* codec_chars.h — GENERATED by tools/gen_c_dict.py from protocol/dictionary.yaml
 * (+ calictl/overrides.py) and calictl/device.py. Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef CODEC_CHARS_H
#define CODEC_CHARS_H
#include <stdint.h>

/* The GATT characteristic short-id map: every function that has a state char,
 * plus the aux chars (version/heartbeat/auth) the app reads/writes on connect
 * (see calictl.device) and the liveness-heartbeat constants that arm control
 * writes (issue #2). All chars share CODEC_UUID_FMT % state_short. */
struct codec_char {
    const char *function;
    uint16_t state_short;  /* the char's 4-hex-digit short id, e.g. 0x1102 */
};
"""


def _env_default(var: str) -> float:
    """The literal default of ``os.environ.get(var, "<default>")`` in ``calictl/device.py``.

    Read from the source (not the imported module) so an environment override the developer
    has set cannot change a generated header.

    :param var: the environment variable name (e.g. ``CALICTL_HEARTBEAT_WARMUP_S``)
    :returns: the default, as a float
    :raises LookupError: no ``os.environ.get(var, "<str literal>")`` call in the module
    """
    import ast

    from calictl import device

    for node in ast.walk(ast.parse(Path(device.__file__).read_text())):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and ast.unparse(node.func.value) == "os.environ"
            and len(node.args) == 2
            and isinstance(node.args[0], ast.Constant)
            and node.args[0].value == var
            and isinstance(node.args[1], ast.Constant)
            and isinstance(node.args[1].value, str)
        ):
            return float(node.args[1].value)
    raise LookupError("no os.environ.get(%r, <literal>) in calictl/device.py" % var)


def generate_chars() -> str:
    """Generate ``codec_chars.h``: the GATT char map + heartbeat constants.

    :returns: the header text (deterministic; sorted function order)
    """
    from calictl import device

    funcs = protocol.load()
    overrides.apply(funcs)
    rows = [
        (name, str(funcs[name].state_char)[4:8].lower()) for name in sorted(funcs) if funcs[name].state_char
    ]

    out = [_CHARS_HEADER]
    out.append("static const struct codec_char CODEC_CHARS[] = {")
    out.extend('    {"%s", 0x%s},' % row for row in rows)
    out.append("};")
    out.append("#define CODEC_NCHARS %d" % len(rows))
    out.append('#define CODEC_UUID_FMT "%s"' % device._aux_uuid("%04x"))
    out.append("#define CODEC_CHAR_VERSION 0x%s" % str(device.VERSION_CHAR)[4:8])
    out.append("#define CODEC_CHAR_HEARTBEAT 0x%s" % str(device.HEARTBEAT_CHAR)[4:8])
    out.append("#define CODEC_CHAR_AUTH 0x%s" % str(device.AUTH_CHAR)[4:8])
    out.append("#define CODEC_HEARTBEAT_START 0x%08xu" % device.HEARTBEAT_START)
    # Timing from calictl.device's DOCUMENTED defaults — the literal default of its
    # os.environ.get(...) call, read from the source (``_env_default``) — so a developer's
    # CALICTL_HEARTBEAT_*_S override (which calictl.device applies at import) can never leak
    # into the committed header.
    period_ms = round(_env_default("CALICTL_HEARTBEAT_PERIOD_S") * 1000)
    warmup_ms = round(_env_default("CALICTL_HEARTBEAT_WARMUP_S") * 1000)
    out.append("#define CODEC_HEARTBEAT_PERIOD_MS %d" % period_ms)
    # calictl.device.read_all waits this long with the heartbeat running before its read pass
    # ("let the liveness register + sensors refresh"); the firmware session does the same.
    out.append("#define CODEC_HEARTBEAT_WARMUP_MS %d" % warmup_ms)
    out.append('#define CODEC_DEVICE_NAME "%s"' % device.DEVICE_NAME)
    out.append("#endif /* CODEC_CHARS_H */")
    return "\n".join(out) + "\n"


_PAIRING_HEADER = """\
/* pairing_consts.h — GENERATED by tools/gen_c_dict.py from calictl/pairing.py.
 * Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef PAIRING_CONSTS_H
#define PAIRING_CONSTS_H
#include <stdint.h>
#include <stddef.h>
"""


def _int_members(mod, prefix: str):
    """(name, value) pairs for module attrs ``prefix``-named ints, sorted by value.

    Filters to ``int`` (excluding ``bool``) so a same-prefixed non-scalar (e.g.
    ``pairing.ERR_NAMES``, a dict) never leaks into an enum.
    """
    items = [
        (k, v)
        for k, v in vars(mod).items()
        if k.startswith(prefix) and isinstance(v, int) and not isinstance(v, bool)
    ]
    return sorted(items, key=lambda kv: kv[1])


def generate_pairing() -> str:
    """Generate ``pairing_consts.h``: the pinned pairing-SM enums/timeouts/names.

    Enum members come from :mod:`calictl.pairing`'s own module attributes (never
    hand-typed here), so a renumbered/renamed constant in the Python SM is
    reflected mechanically rather than silently drifting out of the C port.

    :returns: the header text (deterministic; values sorted ascending)
    """
    from calictl import pairing as P

    states = sorted(P.STATE_NAMES.items())  # [(value, name), ...]
    ev = _int_members(P, "EV_")
    act = _int_members(P, "ACT_")
    err = _int_members(P, "ERR_")

    out = [_PAIRING_HEADER]
    out.append(
        "enum {\n" + ",\n".join("    PAIR_%s = %d" % (name.upper(), val) for val, name in states) + "\n};"
    )
    out.append("enum {\n" + ",\n".join("    PAIR_%s = %d" % (name, val) for name, val in ev) + "\n};")
    out.append("enum {\n" + ",\n".join("    PAIR_%s = %d" % (name, val) for name, val in act) + "\n};")
    out.append("enum {\n" + ",\n".join("    PAIR_%s = %d" % (name, val) for name, val in err) + "\n};")
    out.append("#define PAIR_MAX_ATTEMPTS %d" % P.MAX_ATTEMPTS)

    n = len(states)
    out.append("static const uint16_t PAIR_TIMEOUT_S[%d] = {  /* 0 = no timeout */" % n)
    for st, secs in sorted(P.TIMEOUT_S.items()):
        out.append("    [PAIR_%s] = %d," % (P.STATE_NAMES[st].upper(), secs))
    out.append("};")

    out.append("static const char *const PAIR_STATE_NAMES[%d] = {" % n)
    for _val, name in states:
        out.append('    [PAIR_%s] = "%s",' % (name.upper(), name))
    out.append("};")

    out.append("static const char *const PAIR_ERR_NAMES[%d] = {" % len(err))
    for name, val in err:
        errname = P.ERR_NAMES.get(val)
        out.append("    [PAIR_%s] = %s," % (name, "NULL" if errname is None else '"%s"' % errname))
    out.append("};")

    out.append("#endif /* PAIRING_CONSTS_H */")
    return "\n".join(out) + "\n"


_NET_HEADER = """\
/* net_consts.h — GENERATED by tools/gen_c_dict.py from tools/wifi_consts.py (constants) and
 * tools/wifi_sm_ref.py (the WiFi SM's pinned state/event/action enums). Protocol facts only.
 * DO NOT EDIT. Regenerate: python3 -m tools.gen_c_dict
 *
 * WiFi AP/setup-portal constants shared by the ESP32 firmware and calictl's own setup flow (#154
 * Task 2+). Ruling R1 (Task 6): the setup page is embedded in the firmware as a byte array, never
 * a C string literal, so it never runs through this file's #define text.
 */
#ifndef NET_CONSTS_H
#define NET_CONSTS_H
"""


def generate_net() -> str:
    """Generate ``net_consts.h`` from :data:`tools.wifi_consts.CONSTS` + the WiFi SM enums.

    :returns: the header text (deterministic; sorted key order). A string value becomes a quoted
        ``#define``; an integer key ending in ``_U32`` becomes an 8-digit hex ``#define`` (an
        address, matching ``codec_chars.h``'s ``CODEC_HEARTBEAT_START`` style); every other
        integer becomes a plain decimal ``#define``. Then the pinned ``WIFI_*`` states, ``WEV_*``
        events and ``WACT_*`` actions of :mod:`tools.wifi_sm_ref` (read off the module's own
        attributes, never hand-typed here) as three enums, plus ``WIFI_MAX_ACTIONS``.
    """
    from tools import wifi_consts, wifi_sm_ref

    out = [_NET_HEADER]
    for key in sorted(wifi_consts.CONSTS):
        v = wifi_consts.CONSTS[key]
        if isinstance(v, str):
            out.append('#define %s "%s"' % (key, v))
        elif key.endswith("_U32"):
            out.append("#define %s 0x%08xu" % (key, v))
        else:
            out.append("#define %s %d" % (key, v))
    for prefix in ("WIFI_", "WEV_", "WACT_"):
        out.append("enum {\n" + ",\n".join(
            "    %s = %d" % (name, val) for name, val in _int_members(wifi_sm_ref, prefix)) + "\n};")
    out.append("#define WIFI_MAX_ACTIONS %d" % wifi_sm_ref.MAX_ACTIONS)
    out.append("#endif /* NET_CONSTS_H */")
    return "\n".join(out) + "\n"


def _web_strings() -> dict:
    import json

    return json.loads((WEB_DIR / "strings.json").read_text())


def render_web_page() -> str:
    """Render ``firmware/web/index.html`` into the page the firmware serves (``index_gen.html``).

    :returns: the page with every ``{{NAME}}`` placeholder substituted: ``{{STRINGS}}`` by the
        ``strings.json`` table as compact JSON (``{"key": {"en": …, "de": …}}``, sorted keys), and
        ``{{NET_*}}`` by that :data:`tools.wifi_consts.CONSTS` value (strings unquoted, numbers
        decimal) — so the page never hand-types a constant (e.g. ``NET_PAGE_POLL_MS``).
    :raises KeyError: on a placeholder that names neither.
    """
    import json
    import re

    from tools import wifi_consts

    table = json.dumps(_web_strings(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    # "</" never appears inside the inline <script> (an SSID-free table, but keep it robust)
    table = table.replace("</", "<\\/")

    def sub(m):
        name = m.group(1)
        if name == "STRINGS":
            return table
        return str(wifi_consts.CONSTS[name])

    return re.sub(r"\{\{([A-Z0-9_]+)\}\}", sub, (WEB_DIR / "index.html").read_text())


_WEB_HEADER = """\
/* strings_gen.h — GENERATED by tools/gen_c_dict.py from firmware/web/strings.json and
 * firmware/web/index.html (rendered into firmware/web/index_gen.html). DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 *
 * WEB_STR_EN_* / WEB_STR_DE_*: the status/setup page's EN/DE strings (UTF-8). WEB_INDEX_HTML: the
 * rendered page, byte for byte index_gen.html, as a NUL-terminated byte array (ruling R1: never a
 * C string literal) — the host build serves it; the ESP build embeds the same index_gen.html file.
 * Include from exactly one translation unit (web.c): the array is static.
 */
#ifndef WEB_STRINGS_GEN_H
#define WEB_STRINGS_GEN_H
"""


def generate_web_strings() -> str:
    """Generate ``firmware/web/strings_gen.h``: string macros per ``strings.json`` key + the page.

    :returns: the header text: ``#define WEB_STR_EN_<KEY>``/``WEB_STR_DE_<KEY>`` (keys in file order,
        values as JSON-escaped UTF-8 string literals), then ``WEB_INDEX_HTML_LEN`` and the
        ``static const unsigned char WEB_INDEX_HTML[]`` bytes of :func:`render_web_page` (+ a NUL).
    """
    import json

    out = [_WEB_HEADER]
    for key, tr in _web_strings().items():
        for lang in ("en", "de"):
            out.append("#define WEB_STR_%s_%s %s" % (lang.upper(), key.upper(),
                                                      json.dumps(tr[lang], ensure_ascii=False)))
    page = render_web_page().encode("utf-8")
    out.append("#define WEB_INDEX_HTML_LEN %du" % len(page))
    out.append("static const unsigned char WEB_INDEX_HTML[WEB_INDEX_HTML_LEN + 1] = {")
    data = list(page) + [0]
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    out.append("};")
    out.append("#endif /* WEB_STRINGS_GEN_H */")
    return "\n".join(out) + "\n"


_TARGETS = ((OUT, generate), (CHARS_OUT, generate_chars), (PAIRING_OUT, generate_pairing),
            (NET_OUT, generate_net), (WEB_STRINGS_OUT, generate_web_strings),
            (WEB_PAGE_OUT, render_web_page))


def main() -> int:
    if "--check" in sys.argv:
        stale = [path for path, gen in _TARGETS if not path.is_file() or path.read_text() != gen()]
        if stale:
            print(
                "STALE: %s do not match a fresh regeneration — run "
                "python3 -m tools.gen_c_dict" % ", ".join(str(p) for p in stale),
                file=sys.stderr,
            )
            return 1
        print("fresh: %s" % ", ".join(str(path) for path, _ in _TARGETS))
        return 0
    for path, gen in _TARGETS:
        text = gen()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print("wrote %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
