// @ts-check
// semantics_tables.js — GENERATED by tools/gen_c_dict.py from calictl/semantics.py (+ calictl/control.py)
// — DO NOT EDIT. Regenerate: python3 -m tools.gen_c_dict
// The lookup tables the web UI's JS shares with Python: a classic script loaded before semantics.js and
// app.js (index.html; inlined in the same order into the ESP bundle), so every name below is a global.

/** @type {Record<number, string>} calictl/semantics.py _FRESH_WATER_ALERT */
const SEM_FRESH_WATER_ALERT = {1: "pump_protection", 2: "sensor_error", 3: "error", 7: "error", 4: "pump_error", 5: "empty"};
/** @type {Record<number, string>} calictl/semantics.py _WASTE_WATER_ALERT */
const SEM_WASTE_WATER_ALERT = {1: "full", 2: "sensor_error", 3: "error"};
/** @type {Record<number, string>} calictl/semantics.py _SRC_STATE */
const SEM_SRC_STATE = {0: "inactive", 1: "active", 2: "standby", 6: "init"};
/** @type {string[]} calictl/semantics.py _ENERGY_FAULTS */
const SEM_ENERGY_FAULTS = ["SystemError", "DcdcDefect", "PvDefect", "LandDefect", "LandNotAvailable", "TwoBattNotCharged", "TwoBattSwitchAtCharging", "TwoBattSwitchAtWorkshop", "WarningLevelTwo", "WarningLevelActive", "SleepWarning", "CurrentDeratingTemperature"];
/** @type {Record<number, string>} calictl/semantics.py _COOLER_FAULT */
const SEM_COOLER_FAULT = {1: "error", 2: "emergency", 3: "door_open"};
/** @type {Record<number, string>} calictl/semantics.py _COOLER_QUIET */
const SEM_COOLER_QUIET = {0: "off", 2: "manual", 4: "scheduled"};
/** @type {Record<number, string>} calictl/semantics.py _AIRHEATER_ERROR */
const SEM_AIRHEATER_ERROR = {1: "low_battery", 2: "low_fuel", 3: "system_error", 4: "heating_time_exceeded", 5: "not_possible", 6: "engine_running", 7: "aux_heater_active"};
/** @type {Record<number, string>} calictl/semantics.py _ROOF_POS */
const SEM_ROOF_POS = {0: "closed", 1: "open", 2: "middle", 14: "closed", 15: "error"};
/** @type {Record<number, string>} calictl/semantics.py _ROOF_ALERT */
const SEM_ROOF_ALERT = {1: "child_lock", 4: "error", 5: "driving", 6: "sensor_error", 7: "emergency_locked", 10: "not_possible", 11: "low_battery", 2: "open_checklist", 9: "not_stationary"};
/** @type {Record<string, number>} calictl/semantics.py _LZONES */
const SEM_LZONES = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5, "Six": 6, "Seven": 7, "Eight": 8, "Nine": 9, "OneZero": 10, "OneOne": 11, "OneTwo": 12, "OneThree": 13, "OneFour": 14, "OneFive": 15, "OneSix": 16};
/** @type {string[]} calictl/semantics.py LIGHT_CONFIG_KEYS */
const SEM_LIGHT_CONFIG_KEYS = ["WakeupTimestamp", "WakeupLightValue", "DoorContact", "FavouritesStored"];
/** @type {Set<string>} calictl/semantics.py _DCDC_PLUS2_SW */
const SEM_DCDC_PLUS2_SW = new Set(["0409", "0410"]);
/** @type {Set<string>} calictl/semantics.py _TESTED_AMB_SW */
const SEM_TESTED_AMB_SW = new Set(["0409", "0410"]);
/** @type {number} calictl/semantics.py _TESTED_COMM */
const SEM_TESTED_COMM = 2;
/** @type {Set<string>} calictl/control.py ROOF_MOVE_BLOCK */
const ROOF_MOVE_BLOCK = new Set(["child_lock", "driving", "emergency_locked", "error", "low_battery", "not_possible", "not_stationary"]);
/** @type {Record<string, number>} calictl/control.py ENERGY_MODES */
const CTL_ENERGY_MODES = {"normal": 0, "max_charge": 1, "eco": 2};
/** @type {Record<string, number>} calictl/control.py COOLER_MODES */
const CTL_COOLER_MODES = {"normal": 0, "quiet": 2, "timer_quiet": 4};
/** @type {number[]} calictl/control.py COOLER_LEVEL_RANGE */
const CTL_COOLER_LEVEL_RANGE = [1, 5];
/** @type {number[]} calictl/control.py AIRHEATER_LEVEL_RANGE */
const CTL_AIRHEATER_LEVEL_RANGE = [1, 10];
