/* codec_dict.h — GENERATED by tools/gen_c_dict.py from protocol/dictionary.yaml
 * (+ calictl/overrides.py). Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef CODEC_DICT_H
#define CODEC_DICT_H
#include <stdint.h>

#define CODEC_F_HAS_DEFAULT 0x01
#define CODEC_F_HAS_VALID   0x02  /* valid_mask bit v set => raw value v allowed */

/* Plain struct tags (no typedefs — codec.h owns the codec_func_t typedef and
 * forward-declares the tag, C99-clean): these static tables stay private to
 * codec.c, the only includer of this header. */
struct codec_field {
    const char *name;
    uint16_t offset;      /* bit offset, MSB-first */
    uint8_t  width;       /* 1..32 bits */
    uint8_t  flags;
    uint32_t def;         /* raw default when CODEC_F_HAS_DEFAULT */
    uint32_t valid_mask;  /* when CODEC_F_HAS_VALID */
};

struct codec_func {
    const char *name;
    uint8_t frame_bytes;  /* pinned control frame length; 0 = no control frame */
    const struct codec_field *state_fields;
    uint8_t n_state;
    const struct codec_field *ctrl_fields;
    uint8_t n_ctrl;
};

static const struct codec_field AIRHEATER_STATE[] = {
    {"AirDistribution", 0, 2, 0, 0u, 0x00000000u},
    {"Installed", 3, 1, 0, 0u, 0x00000000u},
    {"FaultTriggerBit", 4, 1, 0, 0u, 0x00000000u},
    {"PermanentOperation", 5, 1, 0, 0u, 0x00000000u},
    {"NormalOperation", 6, 1, 0, 0u, 0x00000000u},
    {"PermanentOperationRequestConfirmation", 7, 1, 0, 0u, 0x00000000u},
    {"HeatingLevel", 8, 4, 0, 0u, 0x00000000u},
    {"ErrorCode", 12, 4, 0, 0u, 0x00000000u},
    {"OperationModeCombined", 16, 4, 0, 0u, 0x00000000u},
    {"OperationModeAirHeater", 20, 4, 0, 0u, 0x00000000u},
    {"RunningTime", 24, 8, 0, 0u, 0x00000000u},
    {"TimerHour", 32, 8, 0, 0u, 0x00000000u},
    {"TimerMin", 40, 8, 0, 0u, 0x00000000u},
    {"RunningTimeinAction", 48, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field AIRHEATER_CTRL[] = {
    {"NormalOperationRequest", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"PermanentOperationConfirmation", 4, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"PermanentOperationRequest", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"AirDistribution", 0, 2, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
    {"HeatingLevel", 12, 4, CODEC_F_HAS_DEFAULT|CODEC_F_HAS_VALID, 11u, 0x00000ffeu},
    {"OperationModeAirHeater", 8, 4, CODEC_F_HAS_DEFAULT, 7u, 0x00000000u},
    {"OperationModeCombined", 20, 4, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
    {"RunningTime", 24, 8, CODEC_F_HAS_DEFAULT, 127u, 0x00000000u},
    {"TimerHour", 32, 8, CODEC_F_HAS_DEFAULT, 31u, 0x00000000u},
    {"TimerMin", 40, 8, CODEC_F_HAS_DEFAULT, 63u, 0x00000000u},
};
static const struct codec_field CAMPINGMODE_STATE[] = {
    {"Installed", 2, 1, 0, 0u, 0x00000000u},
    {"Enable", 3, 1, 0, 0u, 0x00000000u},
    {"InteriorLight", 4, 1, 0, 0u, 0x00000000u},
    {"OutsideLight", 5, 1, 0, 0u, 0x00000000u},
    {"UsbCharger", 6, 1, 0, 0u, 0x00000000u},
    {"State", 7, 1, 0, 0u, 0x00000000u},
};
static const struct codec_field CAMPINGMODE_CTRL[] = {
    {"State", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"UsbCharger", 4, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"OutsideLight", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"InteriorLight", 0, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
};
static const struct codec_field COOLER_STATE[] = {
    {"Error", 0, 2, 0, 0u, 0x00000000u},
    {"NightTimerSet", 3, 1, 0, 0u, 0x00000000u},
    {"Installed", 4, 1, 0, 0u, 0x00000000u},
    {"TimerElapsed", 5, 1, 0, 0u, 0x00000000u},
    {"TimerState", 6, 1, 0, 0u, 0x00000000u},
    {"State", 7, 1, 0, 0u, 0x00000000u},
    {"Mode", 8, 4, 0, 0u, 0x00000000u},
    {"Level", 12, 4, 0, 0u, 0x00000000u},
    {"TimerHourSet", 16, 8, 0, 0u, 0x00000000u},
    {"TimerMinSet", 24, 8, 0, 0u, 0x00000000u},
    {"TimerCounterHour", 32, 8, 0, 0u, 0x00000000u},
    {"TimerCounterMin", 40, 8, 0, 0u, 0x00000000u},
    {"NightTimerHourOn", 48, 8, 0, 0u, 0x00000000u},
    {"NightTimerHourOff", 56, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field COOLER_CTRL[] = {
    {"State", 6, 2, CODEC_F_HAS_DEFAULT|CODEC_F_HAS_VALID, 3u, 0x00000003u},
    {"TimerStart", 4, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"TimerCancel", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"NightTimerSet", 0, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"Level", 12, 4, CODEC_F_HAS_DEFAULT, 7u, 0x00000000u},
    {"Mode", 8, 4, CODEC_F_HAS_DEFAULT, 7u, 0x00000000u},
    {"TimerHour", 16, 8, CODEC_F_HAS_DEFAULT, 30u, 0x00000000u},
    {"TimerMin", 24, 8, CODEC_F_HAS_DEFAULT, 62u, 0x00000000u},
    {"NightTimerHourOn", 32, 8, CODEC_F_HAS_DEFAULT, 31u, 0x00000000u},
    {"NightTimerHourOff", 40, 8, CODEC_F_HAS_DEFAULT, 31u, 0x00000000u},
};
static const struct codec_field ENERGY_STATE[] = {
    {"LandNotAvailable", 0, 1, 0, 0u, 0x00000000u},
    {"LandDefect", 1, 1, 0, 0u, 0x00000000u},
    {"EnergyModeNotSelectable", 2, 1, 0, 0u, 0x00000000u},
    {"DcdcDefect", 3, 1, 0, 0u, 0x00000000u},
    {"WarningLevelActive", 4, 1, 0, 0u, 0x00000000u},
    {"TwoBattSwitchAtWorkshop", 5, 1, 0, 0u, 0x00000000u},
    {"TwoBattSwitchAtCharging", 6, 1, 0, 0u, 0x00000000u},
    {"TwoBattNotCharged", 7, 1, 0, 0u, 0x00000000u},
    {"DcdcInstalled", 8, 1, 0, 0u, 0x00000000u},
    {"LadInstalled", 9, 1, 0, 0u, 0x00000000u},
    {"PvInstalled", 10, 1, 0, 0u, 0x00000000u},
    {"EmpInstalled", 11, 1, 0, 0u, 0x00000000u},
    {"SystemError", 12, 1, 0, 0u, 0x00000000u},
    {"CurrentDeratingTemperature", 13, 1, 0, 0u, 0x00000000u},
    {"SleepWarning", 14, 1, 0, 0u, 0x00000000u},
    {"PvDefect", 15, 1, 0, 0u, 0x00000000u},
    {"SocOneBattAfs", 16, 4, 0, 0u, 0x00000000u},
    {"EnergyMode", 20, 2, 0, 0u, 0x00000000u},
    {"WarningLevelTwo", 22, 2, 0, 0u, 0x00000000u},
    {"StateDcdcAfs", 24, 4, 0, 0u, 0x00000000u},
    {"SocTwoBattAfs", 28, 4, 0, 0u, 0x00000000u},
    {"StatePvAfs", 32, 4, 0, 0u, 0x00000000u},
    {"StateLandAfs", 36, 4, 0, 0u, 0x00000000u},
    {"AgeOneBattValuesMinutes", 40, 8, 0, 0u, 0x00000000u},
    {"IOneBattBemAfs", 48, 8, 0, 0u, 0x00000000u},
    {"PDcdcAfs", 56, 8, 0, 0u, 0x00000000u},
    {"PLandAfs", 64, 8, 0, 0u, 0x00000000u},
    {"PPvAfs", 72, 8, 0, 0u, 0x00000000u},
    {"tTwoBattRemainingh", 80, 8, 0, 0u, 0x00000000u},
    {"tTwoBattRemainingmin", 88, 8, 0, 0u, 0x00000000u},
    {"UOneBattBemAfs", 96, 8, 0, 0u, 0x00000000u},
    {"UTwoBattBemAfs", 104, 8, 0, 0u, 0x00000000u},
    {"ITwoBattBemAfs", 112, 16, 0, 0u, 0x00000000u},
    {"IDcdcAfs", 128, 16, 0, 0u, 0x00000000u},
    {"ILandAfs", 144, 16, 0, 0u, 0x00000000u},
    {"IPvAfs", 160, 16, 0, 0u, 0x00000000u},
};
static const struct codec_field ENERGY_CTRL[] = {
    {"EnergyModeSet", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"DisplayRefresh", 7, 1, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field GENERAL_STATE[] = {
    {"AmbSwVersion", 0, 32, 0, 0u, 0x00000000u},
    {"CmSwVersion", 32, 32, 0, 0u, 0x00000000u},
    {"CommunicationVersion", 64, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field GENERALPURPOSESIGNALS_STATE[] = {
    {"BitZeroEight", 0, 1, 0, 0u, 0x00000000u},
    {"BitZeroSeven", 1, 1, 0, 0u, 0x00000000u},
    {"BitZeroSix", 2, 1, 0, 0u, 0x00000000u},
    {"BitZeroFive", 3, 1, 0, 0u, 0x00000000u},
    {"BitZeroFour", 4, 1, 0, 0u, 0x00000000u},
    {"BitZeroThree", 5, 1, 0, 0u, 0x00000000u},
    {"BitZeroTwo", 6, 1, 0, 0u, 0x00000000u},
    {"BitZeroOne", 7, 1, 0, 0u, 0x00000000u},
    {"ByteZeroOne", 8, 8, 0, 0u, 0x00000000u},
    {"ByteZeroTwo", 16, 8, 0, 0u, 0x00000000u},
    {"ByteZeroThree", 24, 8, 0, 0u, 0x00000000u},
    {"ByteZeroFour", 32, 8, 0, 0u, 0x00000000u},
    {"ByteZeroFive", 40, 8, 0, 0u, 0x00000000u},
    {"ByteZeroSix", 48, 8, 0, 0u, 0x00000000u},
    {"ByteZeroSeven", 56, 8, 0, 0u, 0x00000000u},
    {"ByteZeroEight", 64, 8, 0, 0u, 0x00000000u},
    {"WordZeroOne", 72, 16, 0, 0u, 0x00000000u},
    {"WordZeroTwo", 88, 16, 0, 0u, 0x00000000u},
    {"WordZeroThree", 104, 16, 0, 0u, 0x00000000u},
    {"WordZeroFour", 120, 16, 0, 0u, 0x00000000u},
    {"DwordZeroOne", 136, 32, 0, 0u, 0x00000000u},
};
static const struct codec_field LIGHTING_STATE[] = {
    {"ProfileNumber", 4, 4, 0, 0u, 0x00000000u},
    {"Mode", 8, 8, 0, 0u, 0x00000000u},
    {"Timestamp", 16, 32, 0, 0u, 0x00000000u},
    {"LightValue", 48, 16, 0, 0u, 0x00000000u},
    {"BrightnessLTwo", 64, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOne", 68, 4, 0, 0u, 0x00000000u},
    {"BrightnessLFour", 72, 4, 0, 0u, 0x00000000u},
    {"BrightnessLThree", 76, 4, 0, 0u, 0x00000000u},
    {"BrightnessLSix", 80, 4, 0, 0u, 0x00000000u},
    {"BrightnessLFive", 84, 4, 0, 0u, 0x00000000u},
    {"BrightnessLEight", 88, 4, 0, 0u, 0x00000000u},
    {"BrightnessLSeven", 92, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneZero", 96, 4, 0, 0u, 0x00000000u},
    {"BrightnessLNine", 100, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneTwo", 104, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneOne", 108, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneFour", 112, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneThree", 116, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneSix", 120, 4, 0, 0u, 0x00000000u},
    {"BrightnessLOneFive", 124, 4, 0, 0u, 0x00000000u},
};
static const struct codec_field LIGHTING_CTRL[] = {
    {"ProfileNumber", 4, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"Mode", 8, 8, CODEC_F_HAS_DEFAULT|CODEC_F_HAS_VALID, 0u, 0x11111151u},
    {"Timestamp", 16, 32, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
    {"LightValue", 48, 16, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
    {"BrightnessLOne", 68, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLTwo", 64, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLThree", 76, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLFour", 72, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLFive", 84, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLSix", 80, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLSeven", 92, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLEight", 88, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLNine", 100, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneZero", 96, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneOne", 108, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneTwo", 104, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneThree", 116, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneFour", 112, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneFive", 124, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
    {"BrightnessLOneSix", 120, 4, CODEC_F_HAS_DEFAULT, 14u, 0x00000000u},
};
static const struct codec_field LIVINGROOMHEATER_STATE[] = {
    {"Variant", 0, 2, 0, 0u, 0x00000000u},
    {"Installed", 4, 1, 0, 0u, 0x00000000u},
    {"TemperatureWater", 5, 1, 0, 0u, 0x00000000u},
    {"StateWater", 6, 1, 0, 0u, 0x00000000u},
    {"StateAir", 7, 1, 0, 0u, 0x00000000u},
    {"Error", 8, 4, 0, 0u, 0x00000000u},
    {"Mode", 12, 4, 0, 0u, 0x00000000u},
    {"TemperatureAir", 16, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field LIVINGROOMHEATER_CTRL[] = {
    {"StateAir", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"StateWater", 4, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"TemperatureWater", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"Mode", 12, 4, CODEC_F_HAS_DEFAULT, 5u, 0x00000000u},
    {"TemperatureAir", 16, 8, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field ROOF_STATE[] = {
    {"Position", 0, 4, 0, 0u, 0x00000000u},
    {"Installed", 6, 1, 0, 0u, 0x00000000u},
    {"SafetyCounterValid", 7, 1, 0, 0u, 0x00000000u},
    {"InfoPopUp", 12, 4, 0, 0u, 0x00000000u},
};
static const struct codec_field ROOF_CTRL[] = {
    {"Up", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"Down", 4, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"SafetyCounter", 8, 32, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field ROOFAIRCONDITION_STATE[] = {
    {"Error", 0, 2, 0, 0u, 0x00000000u},
    {"Mode", 2, 2, 0, 0u, 0x00000000u},
    {"Installed", 6, 1, 0, 0u, 0x00000000u},
    {"State", 7, 1, 0, 0u, 0x00000000u},
    {"Fanspeed", 12, 4, 0, 0u, 0x00000000u},
    {"Temperature", 16, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field ROOFAIRCONDITION_CTRL[] = {
    {"State", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"FanSpeed", 12, 4, CODEC_F_HAS_DEFAULT, 7u, 0x00000000u},
    {"Mode", 8, 4, CODEC_F_HAS_DEFAULT, 7u, 0x00000000u},
    {"Temperature", 16, 8, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field SATELLITEANTENNA_STATE[] = {
    {"Error", 0, 4, 0, 0u, 0x00000000u},
    {"System", 4, 2, 0, 0u, 0x00000000u},
    {"Installed", 7, 1, 0, 0u, 0x00000000u},
    {"SatelliteSelection", 8, 4, 0, 0u, 0x00000000u},
    {"Dish", 12, 4, 0, 0u, 0x00000000u},
    {"SignalLevel", 16, 8, 0, 0u, 0x00000000u},
};
static const struct codec_field SATELLITEANTENNA_CTRL[] = {
    {"DishStop", 7, 1, 0, 0u, 0x00000000u},
    {"Wlan", 6, 1, 0, 0u, 0x00000000u},
    {"System", 2, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"Dish", 0, 2, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
    {"SatelliteSelection", 12, 4, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field STAIRS_STATE[] = {
    {"InfoPopUp", 2, 2, 0, 0u, 0x00000000u},
    {"Sensor", 4, 1, 0, 0u, 0x00000000u},
    {"State", 5, 1, 0, 0u, 0x00000000u},
    {"OperationMode", 6, 1, 0, 0u, 0x00000000u},
    {"Installed", 7, 1, 0, 0u, 0x00000000u},
};
static const struct codec_field STAIRS_CTRL[] = {
    {"OperationMode", 6, 2, CODEC_F_HAS_DEFAULT, 3u, 0x00000000u},
    {"Movement", 4, 2, CODEC_F_HAS_DEFAULT, 0u, 0x00000000u},
};
static const struct codec_field VEHICLE_STATE[] = {
    {"CarVariant", 0, 4, 0, 0u, 0x00000000u},
    {"CarLevelPopUp", 4, 2, 0, 0u, 0x00000000u},
    {"TerminalOneFive", 7, 1, 0, 0u, 0x00000000u},
    {"CarTimeYear", 8, 8, 0, 0u, 0x00000000u},
    {"CarTimeMonth", 16, 8, 0, 0u, 0x00000000u},
    {"CarTimeDay", 24, 8, 0, 0u, 0x00000000u},
    {"CarTimeHour", 32, 8, 0, 0u, 0x00000000u},
    {"CarTimeMinute", 40, 8, 0, 0u, 0x00000000u},
    {"CarTimeSecond", 48, 8, 0, 0u, 0x00000000u},
    {"CarLevelRoll", 56, 16, 0, 0u, 0x00000000u},
    {"CarLevelPitch", 72, 16, 0, 0u, 0x00000000u},
};
static const struct codec_field WATER_STATE[] = {
    {"FreshWaterInfoPopUp", 0, 4, 0, 0u, 0x00000000u},
    {"Installed", 6, 1, 0, 0u, 0x00000000u},
    {"FreshWaterUnit", 7, 1, 0, 0u, 0x00000000u},
    {"FreshWaterLevel", 8, 8, 0, 0u, 0x00000000u},
    {"FreshWaterVolume", 16, 8, 0, 0u, 0x00000000u},
    {"WasteWaterInfoPopUp", 26, 2, 0, 0u, 0x00000000u},
    {"WasteWaterUnit", 31, 1, 0, 0u, 0x00000000u},
    {"WasteWaterLevel", 32, 8, 0, 0u, 0x00000000u},
    {"WasteWaterVolume", 40, 8, 0, 0u, 0x00000000u},
};

static const struct codec_func CODEC_FUNCS[] = {
    {"airheater", 6, AIRHEATER_STATE, 14, AIRHEATER_CTRL, 10},
    {"campingmode", 1, CAMPINGMODE_STATE, 6, CAMPINGMODE_CTRL, 4},
    {"cooler", 6, COOLER_STATE, 14, COOLER_CTRL, 10},
    {"energy", 1, ENERGY_STATE, 36, ENERGY_CTRL, 2},
    {"general", 0, GENERAL_STATE, 3, 0, 0},
    {"generalpurposesignals", 0, GENERALPURPOSESIGNALS_STATE, 21, 0, 0},
    {"lighting", 16, LIGHTING_STATE, 20, LIGHTING_CTRL, 20},
    {"livingroomheater", 3, LIVINGROOMHEATER_STATE, 8, LIVINGROOMHEATER_CTRL, 5},
    {"roof", 5, ROOF_STATE, 4, ROOF_CTRL, 3},
    {"roofaircondition", 3, ROOFAIRCONDITION_STATE, 6, ROOFAIRCONDITION_CTRL, 4},
    {"satelliteantenna", 2, SATELLITEANTENNA_STATE, 6, SATELLITEANTENNA_CTRL, 5},
    {"stairs", 1, STAIRS_STATE, 5, STAIRS_CTRL, 2},
    {"vehicle", 0, VEHICLE_STATE, 11, 0, 0},
    {"water", 0, WATER_STATE, 9, 0, 0},
};
#define CODEC_NFUNCS 14
#define CODEC_MAX_FIELDS 36
#define CODEC_MAX_FRAME 32  /* bytes; largest real frame is lighting (16) */
#endif /* CODEC_DICT_H */
