/* codec_chars.h — GENERATED by tools/gen_c_dict.py from protocol/dictionary.yaml
 * (+ calictl/overrides.py) and calictl/device.py. Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef CODEC_CHARS_H
#define CODEC_CHARS_H
#include <stdint.h>

/* The GATT characteristic short-id map: every function that has a state char,
 * plus the aux chars (version/heartbeat/auth) the app reads/writes on connect
 * (see calictl.device) and the liveness-heartbeat constants that arm control
 * writes (issue #2). All chars share CODEC_UUID_FMT % state_short. */
struct codec_char {
    const char *function;
    uint16_t state_short;  /* the char's 4-hex-digit short id, e.g. 0x1102 */
};

static const struct codec_char CODEC_CHARS[] = {
    {"airheater", 0x1702},
    {"campingmode", 0x1202},
    {"cooler", 0x1102},
    {"energy", 0x1602},
    {"general", 0x1001},
    {"generalpurposesignals", 0xf001},
    {"lighting", 0x1502},
    {"livingroomheater", 0x2102},
    {"roof", 0x1402},
    {"roofaircondition", 0x2002},
    {"satelliteantenna", 0x1902},
    {"stairs", 0x1802},
    {"vehicle", 0x1004},
    {"water", 0x1302},
};
#define CODEC_NCHARS 14
#define CODEC_UUID_FMT "0000%04x-6c77-4b7d-bbf6-a5e587701f3d"
#define CODEC_CHAR_VERSION 0x1001
#define CODEC_CHAR_HEARTBEAT 0x1003
#define CODEC_CHAR_AUTH 0x1004
#define CODEC_HEARTBEAT_START 0x00100000u
#define CODEC_HEARTBEAT_PERIOD_MS 600
#define CODEC_HEARTBEAT_WARMUP_MS 2000
#define CODEC_DEVICE_NAME "VWCAMPER"
#endif /* CODEC_CHARS_H */
