/* control_consts.h — GENERATED by tools/gen_c_dict.py from calictl/control.py (+ calictl/semantics.py,
 * protocol/dictionary.yaml + calictl/overrides.py). DO NOT EDIT. Regenerate: python3 -m tools.gen_c_dict
 *
 * Everything the ESP's C control twin (firmware/components/cali_core/control.c) needs from calictl:
 * the write allow-list (CALI_CTL_CHARS: the control char + exact frame length of every function the
 * ESP may write — never the roof's control char), the lighting commit frame, the zone/colour/mode tables,
 * the builders' constants and the gate texts. */
#ifndef CONTROL_CONSTS_H
#define CONTROL_CONSTS_H
#include <stdint.h>

struct cali_ctl_char {
    const char *function;
    uint16_t control_short;  /* the control char's short id, e.g. 0x1101 */
    uint8_t frame_bytes;     /* the only length a write to it may have */
};
struct cali_ctl_zone {
    const char *key;    /* control.LIGHT_ZONES friendly key */
    const char *field;  /* its BrightnessL* control field */
};
struct cali_ctl_name {
    const char *name;
    uint32_t value;
};

static const struct cali_ctl_char CALI_CTL_CHARS[] = {
    {"airheater", 0x1701, 6},
    {"campingmode", 0x1201, 1},
    {"cooler", 0x1101, 6},
    {"energy", 0x1601, 1},
    {"lighting", 0x1501, 16},
};
#define CALI_CTL_NCHARS 5
#define CALI_SENTINEL 3
#define CALI_LIGHT_ON 0
#define CALI_LIGHT_OFF 1
#define CALI_LIGHT_MODE_SET_BRIGHTNESS 4
#define CALI_LIGHT_MODE_SET_COLOR 6
#define CALI_LIGHT_MODE_SET_PROFILE 16
#define CALI_LIGHT_MODE_REQUEST_CONFIG 12
#define CALI_LIGHT_MODE_WAKEUP_TIME 20
#define CALI_LIGHT_PROFILE_DOOR_CONTACT 8
#define CALI_LIGHT_PROFILE_ALL_ON 12
#define CALI_LIGHT_PROFILE_ALL_OFF 0
#define CALI_LIGHT_UNCHANGED 14
#define CALI_LIGHT_MAX_SET 11
#define CALI_LIGHT_BRIGHTNESS_PROFILE 9
#define CALI_AIRHEATER_MAX_RUNTIME_MIN 120
#define CALI_AIRHEATER_MODE_UNCHANGED 7
#define CALI_AIRHEATER_MODE_TIMER_ARMED 3
#define CALI_AIRHEATER_MODE_IDLE 0
#define CALI_AIRHEATER_COMBINED_AIR_HEATER 1
#define CALI_AIRHEATER_LEVEL_UNCHANGED 11
#define CALI_AIRHEATER_RUNTIME_UNCHANGED 127
#define CALI_AIRHEATER_TIMER_HOUR_UNCHANGED 31
#define CALI_AIRHEATER_TIMER_MIN_UNCHANGED 63
static const uint8_t CALI_LIGHT_COMMIT[16] = {0x0e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee};
static const struct cali_ctl_zone CALI_LIGHT_ZONES[] = {
    {"reading-1", "BrightnessLTwo"},
    {"reading-2", "BrightnessLOne"},
    {"reading-3", "BrightnessLFour"},
    {"kitchen", "BrightnessLSeven"},
    {"roof-ambient", "BrightnessLEight"},
    {"outside-rear", "BrightnessLThree"},
    {"kitchen-ambient", "BrightnessLFive"},
    {"kitchen-cabinet", "BrightnessLSix"},
    {"roof-reading", "BrightnessLNine"},
    {"entrance", "BrightnessLOneTwo"},
};
static const char *const CALI_LIGHT_ZONE_FIELDS[] = {"BrightnessLOne", "BrightnessLTwo", "BrightnessLThree", "BrightnessLFour", "BrightnessLFive", "BrightnessLSix", "BrightnessLSeven", "BrightnessLEight", "BrightnessLNine", "BrightnessLOneZero", "BrightnessLOneOne", "BrightnessLOneTwo", "BrightnessLOneThree", "BrightnessLOneFour", "BrightnessLOneFive", "BrightnessLOneSix"};
static const char *const CALI_LIGHT_REAL_ZONE_FIELDS[] = {"BrightnessLOne", "BrightnessLTwo", "BrightnessLThree", "BrightnessLFour", "BrightnessLFive", "BrightnessLSix", "BrightnessLSeven", "BrightnessLEight", "BrightnessLNine", "BrightnessLOneTwo"};
static const struct cali_ctl_name CALI_LIGHT_COLORS[] = {
    {"warm-white", 1},
    {"blood-orange", 2},
    {"amber", 3},
    {"pistachio", 4},
    {"peppermint", 5},
    {"mint", 6},
    {"azure", 7},
    {"dark-blue", 8},
    {"red", 9},
    {"salmon", 10},
};
static const struct cali_ctl_name CALI_COOLER_MODES[] = {
    {"normal", 0},
    {"quiet", 2},
    {"timer_quiet", 4},
};
static const struct cali_ctl_name CALI_ENERGY_MODES[] = {
    {"normal", 0},
    {"max_charge", 1},
    {"eco", 2},
};
static const uint8_t CALI_ROOF_CLOSED_POSITIONS[] = {0, 14};
#define CALI_REASON_CAMPING_NEEDS_MASTER "camping lights and USB need camping mode on (turn the camping master on first)"
#define CALI_REASON_COOLER_STATE_UNKNOWN "the cooler's current schedule is not known yet (no cooler state read) \342\200\224 refusing to overwrite it"
#define CALI_REASON_COOLER_TIMER_NEEDS_FRIDGE_OFF "the cooling timer can only be set while the fridge is off (turn the cooler off first)"
#define CALI_REASON_ENERGY_LOCKED "the unit currently does not allow changing the energy mode"
#define CALI_REASON_FAVOURITE_EMPTY "this favourite is empty on the unit \342\200\224 save it first"
#define CALI_REASON_NOT_ONOFF "the value must be on or off (or true/false, 1/0) \342\200\224 anything else is refused, never read as off"
#define CALI_REASON_QUIET_NEEDS_FRIDGE_ON "quiet mode can only be set while the fridge is on (switch the cooler on first)"
#define CALI_REASON_ROOF_READING "the pop-top roof reading light needs the roof raised (roof is closed)"
#define CALI_REASON_WAKEUP_NO_AREA "the wake-up light needs at least one vehicle area"
#define CALI_REASON_ELSEWHERE "Only via buspi or the app"
#endif /* CONTROL_CONSTS_H */
