/* net_consts.h — GENERATED by tools/gen_c_dict.py from tools/wifi_consts.py (constants) and
 * tools/wifi_sm_ref.py (the WiFi SM's pinned state/event/action enums). Protocol facts only.
 * DO NOT EDIT. Regenerate: python3 -m tools.gen_c_dict
 *
 * WiFi AP/setup-portal constants shared by the ESP32 firmware and calictl's own setup flow (#154
 * Task 2+). Ruling R1 (Task 6): the setup page is embedded in the firmware as a byte array, never
 * a C string literal, so it never runs through this file's #define text.
 */
#ifndef NET_CONSTS_H
#define NET_CONSTS_H

#define NET_AP_ADDR "192.168.4.1"
#define NET_AP_ADDR_U32 0xc0a80401u
#define NET_AP_CLOSE_MS 30000
#define NET_AP_PSK "calictl-setup"
#define NET_AP_SSID "calictl-esp-setup"
#define NET_HOSTNAME "calictl-esp"
#define NET_HTTP_BODY_MAX 16384
#define NET_HTTP_PORT 80
#define NET_HTTP_REQ_MAX 2048
#define NET_JSON_MAX 4096
#define NET_PAGE_POLL_MS 2000
#define NET_PSK_MAX 63
#define NET_PSK_MIN 8
#define NET_RETRY_MAX_MS 60000
#define NET_RETRY_MIN_MS 1000
#define NET_SCAN_MAX 16
#define NET_SETUP_AFTER_MS 300000
#define NET_SSID_MAX 32
enum {
    WIFI_UNPROVISIONED = 0,
    WIFI_SETUP_AP = 1,
    WIFI_CONNECTING = 2,
    WIFI_ONLINE = 3,
    WIFI_RETRYING = 4,
    WIFI_SETUP_AP_RETRYING = 5
};
enum {
    WEV_BOOT_WITH_CREDS = 0,
    WEV_BOOT_NO_CREDS = 1,
    WEV_CREDS_SET = 2,
    WEV_CREDS_FORGET = 3,
    WEV_GOT_IP = 4,
    WEV_LOST = 5,
    WEV_FAILED = 6,
    WEV_AP_STARTED = 7,
    WEV_TICK = 8
};
enum {
    WACT_AP_START = 0,
    WACT_AP_STOP = 1,
    WACT_STA_START = 2,
    WACT_STA_STOP = 3,
    WACT_MDNS = 4,
    WACT_CLEAR_CREDS = 5,
    WACT_LOG_REASON = 6
};
#define WIFI_MAX_ACTIONS 3
#endif /* NET_CONSTS_H */
