/* pairing_consts.h — GENERATED by tools/gen_c_dict.py from calictl/pairing.py.
 * Protocol facts only. DO NOT EDIT.
 * Regenerate: python3 -m tools.gen_c_dict
 */
#ifndef PAIRING_CONSTS_H
#define PAIRING_CONSTS_H
#include <stdint.h>
#include <stddef.h>

enum {
    PAIR_IDLE = 0,
    PAIR_SCANNING = 1,
    PAIR_CONNECTING = 2,
    PAIR_WAITING_PASSKEY = 3,
    PAIR_PAIRING = 4,
    PAIR_VERIFYING = 5,
    PAIR_BONDED = 6,
    PAIR_ERROR = 7,
    PAIR_RESETTING = 8
};
enum {
    PAIR_EV_START = 0,
    PAIR_EV_DEVICE_FOUND = 1,
    PAIR_EV_CONNECTED = 2,
    PAIR_EV_PASSKEY_REQUESTED = 3,
    PAIR_EV_PASSKEY_ENTERED = 4,
    PAIR_EV_PAIR_OK = 5,
    PAIR_EV_PAIR_FAIL = 6,
    PAIR_EV_VERIFY_OK = 7,
    PAIR_EV_VERIFY_FAIL = 8,
    PAIR_EV_TIMEOUT = 9,
    PAIR_EV_CANCEL = 10,
    PAIR_EV_RESET = 11,
    PAIR_EV_RESET_DONE = 12,
    PAIR_EV_CONNECT_FAIL = 13
};
enum {
    PAIR_ACT_START_SCAN = 0,
    PAIR_ACT_STOP_SCAN = 1,
    PAIR_ACT_CONNECT = 2,
    PAIR_ACT_PAIR = 3,
    PAIR_ACT_SEND_PASSKEY = 4,
    PAIR_ACT_VERIFY = 5,
    PAIR_ACT_PERSIST_BOND = 6,
    PAIR_ACT_DISCONNECT = 7,
    PAIR_ACT_REMOVE_BOND = 8
};
enum {
    PAIR_ERR_NONE = 0,
    PAIR_ERR_TIMEOUT = 1,
    PAIR_ERR_PAIR = 2,
    PAIR_ERR_VERIFY = 3,
    PAIR_ERR_CONNECT = 4
};
#define PAIR_MAX_ATTEMPTS 3
static const uint16_t PAIR_TIMEOUT_S[9] = {  /* 0 = no timeout */
    [PAIR_SCANNING] = 30,
    [PAIR_CONNECTING] = 20,
    [PAIR_WAITING_PASSKEY] = 60,
    [PAIR_PAIRING] = 15,
    [PAIR_VERIFYING] = 10,
    [PAIR_RESETTING] = 10,
};
static const char *const PAIR_STATE_NAMES[9] = {
    [PAIR_IDLE] = "idle",
    [PAIR_SCANNING] = "scanning",
    [PAIR_CONNECTING] = "connecting",
    [PAIR_WAITING_PASSKEY] = "waiting_passkey",
    [PAIR_PAIRING] = "pairing",
    [PAIR_VERIFYING] = "verifying",
    [PAIR_BONDED] = "bonded",
    [PAIR_ERROR] = "error",
    [PAIR_RESETTING] = "resetting",
};
static const char *const PAIR_ERR_NAMES[5] = {
    [PAIR_ERR_NONE] = NULL,
    [PAIR_ERR_TIMEOUT] = "timeout",
    [PAIR_ERR_PAIR] = "pairing_failed",
    [PAIR_ERR_VERIFY] = "verify_failed",
    [PAIR_ERR_CONNECT] = "connect_failed",
};
#endif /* PAIRING_CONSTS_H */
